title: Website title
description: Website description
author:
  name: Author Name

nav: # to disable the top navigation bar remove this entry
  elems: # to disable the links in the navbar remove this entry
    - title: Getting Started
      link: getting_started.html
      category: Informations
      weight: 32
    - title: Details
      link: details.html
      category: Informations
      weight: 32
    - title: License
      link: license.html
      category: Legal
      weight: 16
    - title: Authors / Contributors
      link: authors.html
      category: Legal
      weight: 8
    - title: TAR
      link: 'https://github.com/alem0lars/project-website-skeleton/tarball/master'
      category: Downloads
      weight: 4
    - title: ZIP
      link: 'https://github.com/alem0lars/project-website-skeleton/zipball/master'
      category: Downloads
      weight: 4

project_name: Project Website Skeleton
project_desc: Skeleton to create easily create new project websites with services integration
license: gplv2
index_main_button:
  name: Getting Started
  link: getting_started.html

services:
  maven: false # or maven: <relative_pth_to_mvn_root_site>
  github: # or github: false
    user_name: alem0lars
    repo_name: projr
  masterbranch: true
  asana: true
  gemnasium: true
  travis: true
  twitter: alem0lars # or twitter: false
