title: Projr Official Website
description: Main reference for Projr
author:
  name: Alessandro Molari
url: 'http://molarialessandro.info/asd'

nav: # to disable the top navigation bar remove this entry
  elems: # to disable the links in the navbar remove this entry
    - title: Getting Started
      link: getting_started.html
      category: Informations
      weight: 32
    - title: Details
      link: details.html
      category: Informations
      weight: 32
    - title: License
      link: license.html
      category: Legal
      weight: 16
    - title: Authors / Contributors
      link: authors.html
      category: Legal
      weight: 8
    - title: TAR
      link: 'https://github.com/alem0lars/asd/tarball/master'
      category: Downloads
      weight: 4
    - title: ZIP
      link: 'https://github.com/alem0lars/asd/zipball/master'
      category: Downloads
      weight: 4

project_name: Projr
project_desc: Project websites made easy
license: gplv2
index:
  main_button:
    name: Getting Started
    link: getting_started.html
  slideshow:
    theme: bar
    elems:
      - src: 'index/slideshow/manga1.jpg'
      - src: 'index/slideshow/manga2.jpg'
      - src: 'index/slideshow/manga3.jpg'
      - src: 'index/slideshow/manga4.jpg'
  video:
    file: 'index/movie.mp4'
    type: 'video/mp4'
    skin: 'vjs-default'

search: # through Tapir: to enable it you need a token from http://tapirgo.com
  token: 'test-token' # replace it with a valid token

rss:
  files: # They will be expanded => wildcards are allowed (see Dir.glob)
    - 'markup/pages/**'

services:
  github: # or github: false
    user_name: alem0lars
    repo_name: projr
    travis: true
    gemnasium: true
  masterbranch:
    user_name: alem0lars
    badge_type: prof_short # or: cv_long, prof_short, prof_long, resume_short, resume_long
  twitter:
    follow: alem0lars
    share:
      hashtag: 'projr'

  # TODO
  maven: false # or maven: <relative_pth_to_mvn_root_site>
