title: Website title
description: Website description
author:
  name: Author Name
nav:
  elems:
    - title: Home
      link: http://www.example.com
    - title: Nome2
      link: http://www.example.com
    - title: Nome3
      link: http://www.example.com
  downloads:
    - title: TAR
      link: 'https://github.com/alem0lars/project-website-skeleton/tarball/master'
    - title: ZIP
      link: 'https://github.com/alem0lars/project-website-skeleton/zipball/master'

