title: Website title
description: Website description
author:
  name: Author Name

nav: # to disable the top navigation bar remove this entry
  elems: # to disable the links in the navbar remove this entry
    - title: Getting Started
      link: getting_started.html
    - title: Details
      link: details.html
    - title: License
      link: license.html
    - title: Authors / Contributors
      link: authors.html
  downloads: # to disable downloads remove this entry
    - title: TAR
      link: 'https://github.com/alem0lars/project-website-skeleton/tarball/master'
    - title: ZIP
      link: 'https://github.com/alem0lars/project-website-skeleton/zipball/master'

project_name: Project Website Skeleton
project_desc: Skeleton to create easily create new project websites with services integration
index_main_button:
  name: Getting Started
  link: getting_started.html

services:
  maven: false # or maven: <relative_pth_to_mvn_root_site>
  github: # or github: false
    user_name: alem0lars
    repo_name: project-website-skeleton
  hubcap: false
  masterbranch: true
  asana: true
  gemnasium: true
  travis: true
  twitter: alem0lars # or twitter: false
