title: Projr Official Website
description: Main reference for Projr
author:
  name: Alessandro Molari

nav: # to disable the top navigation bar remove this entry
  elems: # to disable the links in the navbar remove this entry
    - title: Getting Started
      link: getting_started.html
      category: Informations
      weight: 32
    - title: Details
      link: details.html
      category: Informations
      weight: 32
    - title: License
      link: license.html
      category: Legal
      weight: 16
    - title: Authors / Contributors
      link: authors.html
      category: Legal
      weight: 8
    - title: TAR
      link: 'https://github.com/alem0lars/projr/tarball/master'
      category: Downloads
      weight: 4
    - title: ZIP
      link: 'https://github.com/alem0lars/projr/zipball/master'
      category: Downloads
      weight: 4

project_name: Projr
project_desc: Skeleton to create easily create new project websites with services integration
license: gplv2
index_main_button:
  name: Getting Started
  link: getting_started.html

services:
  github: # or github: false
    user_name: alem0lars
    repo_name: projr
    travis: true
    gemnasium: true
  masterbranch:
    user_name: alem0lars
    badge_type: prof_short # or: cv_long, prof_short, prof_long, resume_short, resume_long

  # TODO
  maven: false # or maven: <relative_pth_to_mvn_root_site>
  twitter: alem0lars # or twitter: false
